### PR TITLE
Add NSQ

### PR DESCRIPTION
**Pull request by gphat**
# What's this PR do?
Adds an NSQ integration.

# Motivation
To see in NSQ!

r? @rhwlo

### CODE REVIEW

**Comment by gphat** [comment]
Just in case there's slowness or problems adding this to the official DD agent, for which there is [a pull request here](https://github.com/DataDog/dd-agent/pull/2281).

**Comment by rhwlo** [comment]
Could you add tests either here or on the branch you’re asking to merge for https://github.com/DataDog/dd-agent/pull/2281? I’ve poked around at datadog’s testing suite a little bit before, so I’m happy to help out on that part.

**Comment by gphat** [comment]
Hey @rhwlo, I added tests to [Datadog/dd-agent#2281](https://github.com/DataDog/dd-agent/pull/2281) that verify all this works. How's that look?

**Comment by rhwlo** [comment]
Excellent! Do you want me to hold off on merging this until I can take the deploy from https://github.com/stripe-internal/puppet-config/pull/2523 as well?

**Comment by gphat** [comment]
I'll merge this now and assign that one to you to deploy at your leisure.

**Pull request merged**
